"""empty message

Revision ID: 44c716455171
Revises: c8da9517e9d6
Create Date: 2025-05-11 21:08:29.494086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c716455171'
down_revision: Union[str, None] = 'c8da9517e9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'recommendation')
    # ### end Alembic commands ###
